### ISSUE TITLE
--portable rewrite

### ISSUE THREAD

**Issue by git-j** [xrhstosdion/refeus_executable#5]
# as a user i want to start refeus from a removable device to take the data and the configuration from one {windows}pc to another

## developer:
- the executable should detect if it it installed on a removable device and if so apply the REFEUS_SETTINGS_LOCATION to [exe-path]

## tester:
- start refeus.exe from c:/program files, the settings location should be 'registry'
- start refeus.exe from d:/refeus (d assumed to be a removable device), the directory d:/ refeus should now contain a refeus.conf file containing the application settings
- start refeus.exe from c:/user/mydocuments with the parameter --portable, c:/user/mydocuments should now contain a refeus.conf file containing the application settings

## comments from #4 

1: there are api-functions to find out if a given directory is a [network|removable|readonly] device:
http://stackoverflow.com/questions/2854838/given-a-volume-eg-z-how-to-tell-if-that-volume-is-on-a-device-that-is-remov
please remove the implementation that guesses removable device by bin_path.at(0) != 'c', there are valid scenarios to have c:-y: mapped to drives and only z: is removable. 

2: toupper the complete bin-path only for checking the first character and then checking only D-F?
remove the code that uppercases the path, such things should never be done!
try to avoid using char* and <cchar> and <string> functions at all. you will not be able to handle the related memallocs/frees! use the std::string/algorithm equivalents instead, convert std::string to char* right before you call a API-function, convert any returned char* to std::string right after the API-function, use fixed-size buffers(eg char abc[MAX_PATH])

-how does toUpper sort between setEnvironment and split? (->code conventions: functions should be sorted by name)

3: the c:/user location was ment as a example, --portable should also work in c:/myfiles d:/some/sub/directory/to/install/refeus.exe --portable

4: you updated the implementation but not the help text?

try not to read the tester scenarios as 'only this should happen' but as a example to have a idea what could happen

**Comment by xrhstosdion** [comment]
Thanks for the feedback my last implementation was indeed messy, I removed it and added a new one, this time i used GetDriveType(NULL) to recognize the type of the driver, (when null it returns the type of the current drive)

Take in mind that some HDD external drives are recognized as fixed drives (depending on how they are configured), i tried with mine and it was returned as a fixed drive, while my flash drive was returned correct as a removable device.

I made the checks like this, if you want them different let me know :

if (fixed drive or remote network) and --portable
  the REFEUS_SETTINGS_LOCATION is set to current directory
else if fixed drive
  the REFEUS_SETTINGS_LOCATION is set to registry
if drive removable
  the REFEUS_SETTINGS_LOCATION is set current directory

Help text updated
